name: Pull Request Environments

###### Pull Request 'opened' = Provision + Build + Deploy
###### Pull Request 'synchronize' = Build + Deploy
###### Pull Request 'closed' = Destroy
###### Pull Request 'merge' = Destroy

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
######     paths:
######     - 'SampleWebApplication/**'
######     - '!docs/**'

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NUGET_VERSION: '5.3.1' 

jobs:
  provision_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Provision Job
    outputs:
      webapp_name: ${{ steps.output_webapp.outputs.stdout }}
      webapp_url: ${{ steps.output_webapp_url.outputs.stdout }}
      resourcegroup_name: ${{ steps.output_resourcegroup.outputs.stdout }}
    defaults:
      run:
        working-directory: ./infrastructure/pr-environment
    steps:
    - uses: actions/checkout@v2
    - uses: rlespinasse/github-slug-action@master
    - uses: hashicorp/setup-terraform@v1
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}'
        files: '["**/*.tfvars"]'
      env:
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.TENANT_ID }}
        pullrequest_id: ${{ env.GITHUB_REF_SLUG }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config "key=terraform/${{env.GITHUB_REF_SLUG}}" -backend-config "access_key=${{ secrets.TF_VAR_tf_access_key }}"

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: false

    - name: Terraform Plan
      id: plan
      run: terraform plan -var-file="variables.tfvars" -input=false -detailed-exitcode -out=tf_plan
      continue-on-error: true

    - name: Terraform Apply
      id: apply
      run: terraform apply -input=false -auto-approve tf_plan
      continue-on-error: true

    - name: Terraform Output - WebApp
      id: output_webapp
      run: terraform output pr_webapp

    - name: Terraform Output - WebApp Url
      id: output_webapp_url
      run: terraform output pr_webapp_url

    - name: Terraform Output - Resource Group
      id: output_resourcegroup
      run: terraform output resource_group
  
  build_job:
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      runs-on: windows-latest
      needs: provision_job
      name: Build Job
      steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1.1
        with:
          creds: '{ "clientId": "${{ secrets.CLIENT_ID }}", "clientSecret": "${{ secrets.CLIENT_SECRET }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.TENANT_ID }}" }'

      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NUGET_VERSION}}
      - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
        run: nuget restore
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      
      - name: Run MSBuild
        run: msbuild .\SampleWebApplication.sln
        
      - name: 'Run Azure webapp deploy action'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ needs.provision_job.outputs.webapp_name }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/SampleWebApplication/'

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          URL: "https://${{ needs.provision_job.outputs.webapp_url }}"
        with:
          script: |
            const output = `#### Pull Request deployed to Azure App Service 🖌\`
            
            <details><summary>Azure App Service Details</summary>
            
            Your new WebApp is available here: ${process.env.URL}
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  destroy_job:
      if: github.event_name == 'pull_request' && (github.event.action == 'closed' || github.event.pull_request.merged == true)
      runs-on: ubuntu-latest
      name: Destroy Job
      defaults:
        run:
          working-directory: ./infrastructure/pr-environment
      steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@master
      - uses: hashicorp/setup-terraform@v1
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}'
          files: '["**/*.tfvars"]'
        env:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          pullrequest_id: ${{env.GITHUB_REF_SLUG}}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "key=terraform/${{env.GITHUB_REF_SLUG}}" -backend-config "access_key=${{ secrets.TF_VAR_tf_access_key }}"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -var-file="variables.tfvars" -input=false -auto-approve
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          RESOURCEGROUP: ${{ needs.provision_job.outputs.resourcegroup_name }}
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The Azure App Service WebApp for this Pull Request has been deleted, because the Pull Request was closed 🤖'
            })
